version: '3'

services:
  web:
    image: nginx:latest
    restart: unless-stopped
    volumes:
      - ${PWD}/nginx.conf:/etc/nginx/nginx.conf
      - ${PWD}/index.html:/usr/share/nginx/html/index.html
      - ${PWD}/index.fr.htm:/usr/share/nginx/html/index.fr.htm
      - ${PWD}/index.it.htm:/usr/share/nginx/html/index.it.htm
      - ${PWD}/img:/usr/share/nginx/html/img
      - ${PWD}/css:/usr/share/nginx/html/css
      - ${PWD}/js:/usr/share/nginx/html/js
      - ${PWD}/scss:/usr/share/nginx/html/scss
      - ${PWD}/fonts:/usr/share/nginx/html/fonts
      - ${PWD}/data_certbot/certbot/conf:/etc/letsencrypt
      - ${PWD}/data_certbot/certbot/www:/var/www/certbot
    ports:
      - "80:80"
      - "443:443"
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"

  certbot:
    image: certbot/certbot
    restart: unless-stopped
    volumes:
      - ${PWD}/data_certbot/certbot/conf:/etc/letsencrypt
      - ${PWD}/data_certbot/certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"

  api:
    build: ./api/v1
    expose:
      - "5000"
    environment:
      - EASYWED_SECRET=${EASYWED_SECRET}
      - EASYWED_PWD=${EASYWED_PWD}
      - DB_USER=${DB_USER}
      - DB_PWD=${DB_PWD}

  db-api:
    build: ./api
    ports:
      - "27017:27017"
    volumes:
      - ./data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${DB_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${DB_PWD}
